# apps/api/Dockerfile.dev
FROM node:22-slim

WORKDIR /app

# 시스템 라이브러리
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

# 패키지 매니저 pnpm 설치
RUN npm install -g pnpm

# 모노레포 구조를 위해 루트 파일들 복사
COPY package.json ./

# 의존성 설치
RUN pnpm install

# 소스 코드는 볼륨 마운트할 거라 COPY 안 함

CMD ["npm", "run", "start:dev"]